# Generated by Django 3.2.5 on 2021-07-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bankbranch_options'),
        ('account', '0003_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_work',
            field=models.DateField(blank=True, verbose_name='End of work date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_work',
            field=models.DateField(blank=True, verbose_name='Start of work date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.workgroup', verbose_name='Work group'),
        ),
    ]
