# Generated by Django 3.2.5 on 2021-07-06 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Child name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Sex')),
                ('has_impact', models.BooleanField(default=False, verbose_name='Has impact on payslip?')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ('-pk',),
            },
        ),
    ]
