# Generated by Django 3.2.5 on 2021-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210706_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_work',
            field=models.DateField(verbose_name='Start of work date'),
        ),
    ]
