# Generated by Django 3.2.5 on 2021-07-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='military_service',
            field=models.IntegerField(choices=[(1, 'Exempted from military service'), (2, 'End of  military service'), (3, 'Subject to military service'), (4, 'fugitive'), (5, 'Exempted due to study'), (6, 'Temporary Exempted'), (7, 'Female'), (8, 'Unknown')], default=8, verbose_name='Military service status'),
        ),
    ]
