# Generated by Django 3.2.5 on 2021-07-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210719_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permission',
            new_name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
