version: "3.9"
   
services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - djangonetwork
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - db
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: mojixcoder@gmail.com
            PGADMIN_DEFAULT_PASSWORD: pawndarby
        restart: always
        ports:
            - "5050:80"
    web:
        build: .
        command: python manage.py runserver 0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - db
        networks:
            - djangonetwork


networks:
    djangonetwork:
        driver: bridge
