# Generated by Django 3.2.5 on 2021-07-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('icon', models.ImageField(upload_to='bank/', verbose_name='Icon')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Province name')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('daily', models.IntegerField(verbose_name='Daily')),
                ('overtime', models.IntegerField(verbose_name='Overtime')),
                ('has_payslip', models.BooleanField(default=False, verbose_name='Has payslip')),
            ],
            options={
                'verbose_name': 'Work Group',
                'verbose_name_plural': 'Work Groups',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('year', models.IntegerField(unique=True, verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('month_number', models.IntegerField(verbose_name='Month number')),
                ('days', models.IntegerField(verbose_name='Number of days')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='core.year', verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='City name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('province', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Branch name')),
                ('first_name', models.CharField(max_length=255, verbose_name='Manager first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Manager last name')),
                ('what_type', models.IntegerField(choices=[(1, 'Branch'), (2, 'Sales Agent')], default=1, verbose_name='Branch type')),
                ('tel1', models.CharField(max_length=100, verbose_name='Tel1')),
                ('tel2', models.CharField(blank=True, max_length=100, verbose_name='Tel2')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='core.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branchs',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Branch name')),
                ('branch_code', models.CharField(max_length=10, verbose_name='Branch code')),
                ('address', models.TextField(verbose_name='Address')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='Telephone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Manager name')),
                ('fax_number', models.CharField(blank=True, max_length=255, verbose_name='Fax number')),
                ('manager_number', models.CharField(blank=True, max_length=255, verbose_name='Manager phone number')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_branchs', to='core.bank', verbose_name='Bank')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_branchs', to='core.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'شعبه بانک\u200cها',
                'verbose_name_plural': 'شعب بانک\u200cها',
                'ordering': ('bank', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.UniqueConstraint(fields=('year', 'month_number'), name='year_month_unique'),
        ),
        migrations.AddConstraint(
            model_name='bankbranch',
            constraint=models.UniqueConstraint(fields=('branch_code', 'bank'), name='unique_branch_code_bank'),
        ),
    ]
